### ISSUE TITLE
Hay!!

### ISSUE THREAD

**Issue by ChiruMori** [JesseGuoTechnology/Hello-World#1]
Hello，我是 ChiruMori，在你这里写个 Issue 不介意吧~(doge

**Comment by JesseGuoTech** [comment]
Hi，这里是JesseGuo，感谢您对(只会写Hello World的)新人的支持！

**Comment by ChiruMori** [comment]
哪里哪里，我也是 EverMC 玩家，Java 的问题可以一起探讨，Issue 先关啦。
